application: quizer-gapp
version: 4
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
  
- url: /css
  static_dir: css

- url: /img
  static_dir: img
  
- url: /js
  static_dir: js

- url: /.*
  script: script.app

libraries:
- name: jinja2
  version: latest
